name: Lint Python

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main
      - lint-action
    paths:
        - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pylint
          path: ./pylint/
          if-no-files-found: error