name: Lint Python

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main
      - lint-action
    paths:
        - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: python:3.11-alpine
    steps:
      - name: Install Git
        run: |
          apk add git
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip install pylint black pre-commit
      - name: Run linters
        run: |
          pwd
          git --version
          black --version
          pylint --version
          mkdir ./pylint
          pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref ${{ github.sha }}      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pylint
          path: ./pylint/
          if-no-files-found: error